import type { AdminUser, EditLog, ImportJob, PendingImport, PermissionRule, UploadRecord } from "./types";

export const demoImportJobs: ImportJob[] = [
  {
    id: "demo-running-monkey",
    batchId: "B-20260715-01",
    batchName: "2026-07-15 · Monkey Headcover",
    status: "running",
    progress: 58,
    total: 2,
    completed: 1,
    failed: 0,
    createdBy: "本地模拟",
    createdAt: "刚刚",
    finishedAt: null,
    dismissedAt: null,
    items: [
      { importId: 101, name: "IMG_6012318_monkey_back.jpg", relPath: "临时 / 2026-07-15 / 产品图片", status: "completed", progress: 100, stage: "completed", error: "" },
      { importId: 102, name: "IMG_6012318_monkey_front.jpg", relPath: "临时 / 2026-07-15 / 产品图片", status: "uploading", progress: 58, stage: "uploading", error: "" },
    ],
  },
  {
    id: "demo-partial-covers",
    batchId: "B-DEMO-IMPORT-02",
    batchName: "模拟批次 · Tarot Driver Cover",
    status: "partial",
    progress: 83,
    total: 6,
    completed: 4,
    failed: 1,
    createdBy: "本地模拟",
    createdAt: "1 分钟前",
    finishedAt: Date.now() - 60_000,
    dismissedAt: null,
    items: [
      { importId: 9101, name: "6016297-front.jpg", relPath: "临时 / 模拟 / Tarot", status: "completed", progress: 100, stage: "completed", error: "" },
      { importId: 9102, name: "6016297-back.jpg", relPath: "临时 / 模拟 / Tarot", status: "completed", progress: 100, stage: "completed", error: "" },
      { importId: 9103, name: "6016297-side.jpg", relPath: "临时 / 模拟 / Tarot", status: "completed", progress: 100, stage: "completed", error: "" },
      { importId: 9104, name: "6016297-detail.jpg", relPath: "临时 / 模拟 / Tarot", status: "completed", progress: 100, stage: "completed", error: "" },
      { importId: 9105, name: "6016297-opening.jpg", relPath: "临时 / 模拟 / Tarot", status: "error", progress: 72, stage: "error", error: "模拟失败：目标文件名重复" },
      { importId: 9106, name: "6016297-package.jpg", relPath: "临时 / 模拟 / Tarot", status: "uploading", progress: 28, stage: "uploading", error: "" },
    ],
  },
  {
    id: "demo-completed-knit",
    batchId: "B-DEMO-IMPORT-03",
    batchName: "模拟批次 · Knit Headcover Set",
    status: "completed",
    progress: 100,
    total: 3,
    completed: 3,
    failed: 0,
    createdBy: "本地模拟",
    createdAt: "3 分钟前",
    finishedAt: null,
    dismissedAt: null,
    items: [
      { importId: 9201, name: "6007907-driver.jpg", relPath: "临时 / 模拟 / Knit", status: "completed", progress: 100, stage: "completed", error: "" },
      { importId: 9202, name: "6007907-fairway-3.jpg", relPath: "临时 / 模拟 / Knit", status: "completed", progress: 100, stage: "completed", error: "" },
      { importId: 9203, name: "6007907-fairway-5.jpg", relPath: "临时 / 模拟 / Knit", status: "completed", progress: 100, stage: "completed", error: "" },
    ],
  },
];

export const initialPendingImports: PendingImport[] = [
  {
    id: 101,
    revision: 0,
    batchId: "B-20260715-01",
    batchName: "2026-07-15 · Monkey Headcover",
    name: "IMG_6012318_monkey_back.jpg",
    relPath: "临时 / 2026-07-15 / 产品图片",
    thumbnailUrl: "/assets/monkey-driver-cover-alt.jpg",
    mediaUrl: "",
    status: "suggested",
    confidence: 0.94,
    reason: "文件名与现有猴子系列 SKU 命名规则高度匹配。",
    sku: "6012318",
    englishName: "Tailored Monkey Driver Headcover",
    driveFolder: "04 Product Images / Craftsman Golf / Driver Headcovers / 6012318",
    driveName: "6012318-tailored-monkey-driver-headcover-back.jpg",
    assetType: "image",
    setCode: "Set00264",
    categoryId: "HC_DRIVER",
    categoryTags: ["PLUSH_ANIMAL"],
    themes: ["ANIMALS"],
    categoryConfidence: 0.98,
    categorySource: "sku_inheritance",
    categoryReason: "已继承该 SKU 的审核分类。",
    categoryNeedsReview: false,
    discoveredAt: "今天 10:42",
  },
  {
    id: 102,
    revision: 0,
    batchId: "B-20260715-01",
    batchName: "2026-07-15 · Monkey Headcover",
    name: "IMG_6012318_monkey_front.jpg",
    relPath: "临时 / 2026-07-15 / 产品图片",
    thumbnailUrl: "/assets/monkey-driver-cover.jpg",
    mediaUrl: "",
    status: "suggested",
    confidence: 0.94,
    reason: "文件名与现有猴子系列 SKU 命名规则高度匹配。",
    sku: "6012318",
    englishName: "Tailored Monkey Driver Headcover",
    driveFolder: "04 Product Images / Craftsman Golf / Driver Headcovers / 6012318",
    driveName: "6012318-tailored-monkey-driver-headcover-front.jpg",
    assetType: "image",
    setCode: "Set00264",
    categoryId: "HC_DRIVER",
    categoryTags: ["PLUSH_ANIMAL"],
    themes: ["ANIMALS"],
    categoryConfidence: 0.98,
    categorySource: "sku_inheritance",
    categoryReason: "已继承该 SKU 的审核分类。",
    categoryNeedsReview: false,
    discoveredAt: "今天 10:39",
  },
  {
    id: 107,
    revision: 0,
    batchId: "B-20260715-01",
    batchName: "2026-07-15 · Monkey Headcover",
    name: "IMG_6012318_monkey_side.jpg",
    relPath: "临时 / 2026-07-15 / 产品图片",
    thumbnailUrl: "/assets/monkey-driver-cover.jpg",
    mediaUrl: "",
    status: "suggested",
    confidence: 0.94,
    reason: "文件名与现有猴子系列 SKU 命名规则高度匹配。",
    sku: "6012318",
    englishName: "Tailored Monkey Driver Headcover",
    driveFolder: "04 Product Images / Craftsman Golf / Driver Headcovers / 6012318",
    driveName: "6012318-tailored-monkey-driver-headcover-side.jpg",
    assetType: "image",
    setCode: "Set00264",
    categoryId: "HC_DRIVER",
    categoryTags: ["PLUSH_ANIMAL"],
    themes: ["ANIMALS"],
    categoryConfidence: 0.98,
    categorySource: "sku_inheritance",
    categoryReason: "已继承该 SKU 的审核分类。",
    categoryNeedsReview: false,
    discoveredAt: "今天 10:37",
  },
  {
    id: 108,
    revision: 0,
    batchId: "B-20260715-01",
    batchName: "2026-07-15 · Monkey Headcover",
    name: "IMG_6012318_monkey_detail.jpg",
    relPath: "临时 / 2026-07-15 / 产品图片",
    thumbnailUrl: "/assets/monkey-driver-cover-alt.jpg",
    mediaUrl: "",
    status: "suggested",
    confidence: 0.94,
    reason: "文件名与现有猴子系列 SKU 命名规则高度匹配。",
    sku: "6012318",
    englishName: "Tailored Monkey Driver Headcover",
    driveFolder: "04 Product Images / Craftsman Golf / Driver Headcovers / 6012318",
    driveName: "6012318-tailored-monkey-driver-headcover-detail.jpg",
    assetType: "image",
    setCode: "Set00264",
    categoryId: "HC_DRIVER",
    categoryTags: ["PLUSH_ANIMAL"],
    themes: ["ANIMALS"],
    categoryConfidence: 0.98,
    categorySource: "sku_inheritance",
    categoryReason: "已继承该 SKU 的审核分类。",
    categoryNeedsReview: false,
    discoveredAt: "今天 10:36",
  },
  {
    id: 103,
    revision: 0,
    batchId: "B-TH-EXPO-36",
    batchName: "Thailand Expo · T36",
    name: "T36_invitation_v8.png",
    relPath: "临时 / Thailand Expo / approved",
    thumbnailUrl: "/assets/thailand-golf-expo.png",
    mediaUrl: "",
    status: "pending",
    confidence: null,
    reason: "尚未生成建议。",
    sku: "",
    englishName: "",
    driveFolder: "",
    driveName: "T36_invitation_v8.png",
    assetType: "ads",
    setCode: "",
    categoryId: "",
    categoryTags: [],
    themes: [],
    categoryConfidence: 0,
    categorySource: "",
    categoryReason: "活动素材不属于产品分类。",
    categoryNeedsReview: true,
    discoveredAt: "今天 09:58",
  },
  {
    id: 104,
    revision: 0,
    batchId: "B-ID-PKG-25",
    batchName: "Payakumbuh Event · 2025",
    name: "Payakumbuh_event_lockup.png",
    relPath: "临时 / Indonesia / sponsorship",
    thumbnailUrl: "/assets/payakumbuh-logo.png",
    mediaUrl: "",
    status: "error",
    confidence: 0.42,
    reason: "无法从文件名确定活动年份。",
    error: "目标目录缺少年份，请人工确认后保存。",
    sku: "EVT-PKG-25",
    englishName: "Payakumbuh Golf Tournament",
    driveFolder: "07 Event Sponsorships / Indonesia / Payakumbuh Golf Tournament",
    driveName: "payakumbuh-event-lockup.png",
    assetType: "ads",
    setCode: "",
    categoryId: "",
    categoryTags: [],
    themes: [],
    categoryConfidence: 0,
    categorySource: "",
    categoryReason: "活动素材不属于产品分类。",
    categoryNeedsReview: true,
    discoveredAt: "昨天 18:21",
  },
  {
    id: 105,
    revision: 0,
    batchId: "B-TACO-0726",
    batchName: "Happy Taco Campaign",
    name: "Happy_Taco_Campaign_01.jpg",
    relPath: "临时 / Big Crazy / campaign",
    thumbnailUrl: "/assets/happy-taco-putter-set.jpg",
    mediaUrl: "",
    status: "pending",
    confidence: null,
    reason: "尚未生成建议。",
    sku: "",
    englishName: "",
    driveFolder: "",
    driveName: "Happy_Taco_Campaign_01.jpg",
    assetType: "ads",
    setCode: "",
    categoryId: "",
    categoryTags: [],
    themes: [],
    categoryConfidence: 0,
    categorySource: "",
    categoryReason: "尚未生成分类建议。",
    categoryNeedsReview: true,
    discoveredAt: "昨天 17:40",
  },
  {
    id: 106,
    revision: 0,
    batchId: "B-ARCHIVE-0725",
    batchName: "July sample · Paused",
    name: "6012240_taco_lifestyle_alt.jpg",
    relPath: "临时 / Big Crazy / paused",
    thumbnailUrl: "/assets/happy-taco-putter-set.jpg",
    mediaUrl: "",
    status: "rejected",
    confidence: 0.88,
    reason: "暂不需要入库，素材与建议均已保留。",
    sku: "6012240",
    englishName: "Happy Taco Putter Collection",
    driveFolder: "04 Product Images / Big Crazy / Putter Covers / 6012240",
    driveName: "6012240-happy-taco-putter-lifestyle-alt.jpg",
    assetType: "image",
    setCode: "",
    categoryId: "HC_PUTTER_BLADE",
    categoryTags: [],
    themes: ["FOOD_DRINKS"],
    categoryConfidence: 0.94,
    categorySource: "sku_inheritance",
    categoryReason: "已继承该 SKU 的审核分类。",
    categoryNeedsReview: false,
    discoveredAt: "7 月 25 日",
  },
];

export const initialUsers: AdminUser[] = [
  { id: 1, email: "admin@craftsmangolf.com", name: "Lina", role: "管理员", permissionMode: "role_default", disabled: false, createdAt: "2026-05-12" },
  { id: 2, email: "marketing@craftsmangolf.com", name: "Marketing CN", role: "内部员工", permissionMode: "role_default", disabled: false, createdAt: "2026-05-18" },
  { id: 3, email: "apac-sales@craftsmangolf.com", name: "APAC Sales", role: "内部员工", permissionMode: "role_default", disabled: false, createdAt: "2026-06-02" },
  { id: 4, email: "partner@example.com", name: "Overseas Partner", role: "海外客户", permissionMode: "allowlist", disabled: false, createdAt: "2026-06-26" },
];

export const initialRules: PermissionRule[] = [
  { id: 1, role: "海外客户", scope: "素材类型", value: "kol_ugc", createdAt: "2026-06-12" },
  { id: 2, role: "国内客户", scope: "其他标签", value: "_internal", createdAt: "2026-06-12" },
  { id: 3, role: "服务商", scope: "品牌", value: "Big Crazy", createdAt: "2026-07-01" },
];

export const editLogs: EditLog[] = [
  { id: 1, material: "6012159 / monkey-front.jpg", field: "英文品名", before: "Monkey Cover", after: "Quilted Monkey Driver Headcover", editor: "Lina", createdAt: "今天 09:12" },
  { id: 2, material: "EVT-T36 / invitation.png", field: "素材类型", before: "image", after: "ads", editor: "Marketing CN", createdAt: "昨天 17:31" },
  { id: 3, material: "6012188 / group.jpg", field: "目标目录", before: "Fairway", after: "Fairway Headcovers / 6012188", editor: "Amy", createdAt: "昨天 14:06" },
];

export const uploadHistory: UploadRecord[] = [
  { id: 1, sku: "6012159", name: "monkey-front-lifestyle.jpg", destination: "Driver Headcovers / 6012159", operator: "Lina", createdAt: "今天 09:35", thumbnailUrl: "/assets/monkey-driver-cover.jpg" },
  { id: 2, sku: "6012188", name: "woodland-group.jpg", destination: "Fairway Headcovers / 6012188", operator: "Amy", createdAt: "昨天 16:18", thumbnailUrl: "/assets/woodland-headcover-set.jpg" },
  { id: 3, sku: "6012034", name: "player-series-set.jpg", destination: "Knit Headcovers / 6012034", operator: "Lina", createdAt: "昨天 11:02", thumbnailUrl: "/assets/player-knit-set.jpg" },
];
